---
- name: Install Clickhouse & Vector
  hosts: clickhouse-01
  become: true
  tasks:
    - name: Get clickhouse distrib
      get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-22.3.3.44.noarch.rpm"
        dest: "./{{ item }}-22.3.3.44.rpm"
      loop:
        - clickhouse-client
        - clickhouse-server
        - clickhouse-common-static
      ignore_errors: yes

    - name: Install clickhouse packages
      apt:
        deb: "./{{ item }}-22.3.3.44.deb"
        state: present
      loop:
        - clickhouse-client
        - clickhouse-server
        - clickhouse-common-static
      when: ansible_facts.pkg_mgr == "apt"
