- name: Install Clickhouse and Vector
  hosts: clickhouse
  become: true

  tasks:
    - name: Install necessary dependencies
      ansible.builtin.apt:
        name:
          - python3-paramiko
          - python3-pycurl
          - python3-pip
        state: present

    - name: Install python3-venv
      ansible.builtin.apt:
        name: python3-venv
        state: present

    - name: Create a virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /opt/venv
      args:
        creates: /opt/venv/bin/activate

    - name: Install Paramiko in virtual environment
      ansible.builtin.command:
        cmd: /opt/venv/bin/pip install paramiko
      register: paramiko_install
      changed_when: "'Successfully installed' in paramiko_install.stdout"

    - name: Get Clickhouse distrib
      ansible.builtin.get_url:
        url: "https://github.com/ClickHouse/ClickHouse/releases/download/v24.8.5.115-lts/clickhouse-client-24.8.5.115-amd64.tgz"
        dest: "/tmp/clickhouse.tgz"
        mode: '0644'

    - name: Create directory for Clickhouse extraction
      ansible.builtin.file:
        path: /tmp/clickhouse
        state: directory
        mode: '0755'

    - name: Verify Clickhouse directory exists
      ansible.builtin.stat:
        path: /tmp/clickhouse
      register: clickhouse_dir

    - name: Extract Clickhouse package
      ansible.builtin.unarchive:
        src: "/tmp/clickhouse.tgz"
        dest: "/tmp/clickhouse"
        remote_src: true
      when: clickhouse_dir.stat.exists

    - name: Check if Clickhouse client is installed
      ansible.builtin.stat:
        path: /usr/bin/clickhouse-client
      register: clickhouse_client

    - name: Install Clickhouse client
      ansible.builtin.command:
        cmd: dpkg -i /tmp/clickhouse/clickhouse-client-24.8.5.115-amd64.deb
      when: not clickhouse_client.stat.exists
      changed_when: true

    - name: Ensure Clickhouse service is running
      ansible.builtin.service:
        name: clickhouse-server
        state: started

