---
clickhouse_database_name: logs
clickhouse_create_table_name: dummy_logs
clickhouse_version: "24.7.3.42"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
